apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ipconfig-service.fullname" . }}
  labels:
    app: ipconfig-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ipconfig-service
  template:
    metadata:
      labels:
        app: ipconfig-service
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: ipconfig-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
