apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipconfig-service.fullname" . }}
  labels:
    app: ipconfig-service
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: ipconfig-service
